require: rubocop-rspec

AllCops:
  RSpec:
    Patterns:
    - '_spec.rb$'

Documentation:
    Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/**/booking_handler_spec.rb'
